@startuml
!include <C4/C4_Context>

Person(client, "Клиент")
Person(operator, "Оператор кол-центра")
Person(front, "Менеджер фронт офиса")
Person(back, "Менеджер бэк офиса")

System(service, "Сервис заявок на депозиты")
System(website,"Сайт")
System(app,"Интернет банк")
System(abs,"АБС")
System(callCenter,"Кол-центр")
System(sms,"СМС Шлюз")

Rel(client, website, "Отправляет заявку на депозит")
Rel(client, app, "Отправляет заявку на депозит")
Rel(back, abs, "Cогласовывает заявки")
Rel(abs, sms, "Подтверждение через СМС")
Rel(operator, callCenter, "Оформляет заявки")
Rel(front, abs, "Подтверждает данные по заявке")

Rel(app, service, "Создание заявки")
Rel(website, callCenter, "Передача данных для оформления")
Rel(operator, service, "Создание заявки")

Rel(service, abs, "Отправляет заявки")

@enduml 

